version: '3'
services:
    api:
        volumes:
        - /var/www/node_modules
        - ./Webserver:/var/www
        container_name: typscript_nodeserver
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /var/www
        ports:
        - "3010:3010"